export const content = {
  hero: {
    title: "WINSIGHTS",
    subtitle: "LEARN THE FINANCIAL MARKETS WITH EASE!",
    description: `Join our flourishing community which is making thousands daily, and catered for all skill levels!`,
    cta: "Join Now",
    subscriptionUrl: "https://buy.stripe.com/aEU9AVdWd7GU4iAaEM",
  },
  whoWeAre: {
    title: "Why WINSIGHTS?",
    description: "Our signals, your education, your profits",
    mainContent: "At Winsights, we cater to all skill levels from complete novices to full-time funded traders. For £30 a month, you get 1:1 support, 24/7 help, 96% win rate signals, and an incredible community! We provide market-leading insights with daily analysis and real-time alerts, comprehensive macro research reports, and educational guides covering beginner to expert levels, ensuring every member builds a foundation for long-term trading success.",
    price: "£30",
    pricePeriod: "a month",
    features: [
      {
        title: "Custom Bloomberg-esque newsfeed",
        description: "Instant global news delivered to your phone!",
      },
      {
        title: "24/7 Help",
        description: "Round-the-clock assistance whenever you need it",
      },
      {
        title: "89.6% Win Rate",
        description: "Highly accurate trading signals and insights",
      },
      {
        title: "Incredible Community",
        description: "Join thousands of traders sharing knowledge",
      },
    ],
  },
  success: {
    title: "Our Success",
    metrics: [
      { value: "400+", label: "TRADERS" },
      { value: "89.6%", label: "WINRATE IN ALL MARKETS" },
      { value: "£3M+", label: "GROUP PROFIT" },
      { value: "£30", label: "PER MONTH ONLY" },
    ],
  },
  testimonials: [
    {
      name: "Berkay",
      age: 20,
      content: "After joining Winsights I've learned a lot more about the crypto and trading space with a lot of helpful and insightful information. The community and help you get from everyone is unmatched and any question you ask is given a clear and useful response. I started off by spot buying into a coin called ONDO and in a matter of months I multiplied my money as well With the help of the leverage calls I've been able to pay the monthly fee easily. This experience has taught me to be responsible with my money and gain patience as well as meet new friends who are also on the same path to success.",
      rating: 5,
    },
    {
      name: "Loz",
      age: 29,
      content: "Been chucking money in rubbish savings getting pennies for years. Learning about ISAs, pensions, tax dodging has been game changing. Finally understand bond stuff and can actually read central bank chat without my brain melting. Their stock picks absolutely rinse my old fund manager.",
      rating: 5,
    },
    {
      name: "Haruun",
      age: 21,
      content: "Prior to joining Winsights, I had little to no knowledge of fundamentals in forex & crypto, I've now been in the group for almost 2 years and I'm glad to say my knowledge has expanded whether it's from directly asking questions or soaking in knowledge from members, the group offers simple yet effective videos such as crypto outlooks which really helped with my understanding, this group is far from just a signal service group & for the price, it's stupid not to join!",
      rating: 5,
    },
    {
      name: "Harry",
      age: 24,
      content: "Used to think crypto was just gambling and forex was too complicated. Man was I wrong! The guides break everything down so simply, even chart reading makes sense now. Passed my first funded account thanks to their gbp calls, community went mad celebrating with me which was class. Love how they explain the reasoning behind trades instead of just saying \"buy this.\"",
      rating: 5,
    },
    {
      name: "Hussain",
      age: 24,
      content: "Was proper skint as a student, started with like £50. Admins were absolute legends showing me how to start small and not be an idiot. Uni's useless for real money knowledge, compound interest, leverage, all that. Crypto lot taught me yield farming and staking stuff, now making money doing nothing. That £50's now £800+ and I actually know what I'm doing with money.",
      rating: 5,
    },
    {
      name: "Rizwan",
      age: 36,
      content: "Got kids so can't be taking mad risks with family money. These guys taught me proper risk management, diversification, stop losses, all the important boring stuff that actually works. Macro research helps me think long term about investments. Trade around work no problem now. Even set up junior ISAs for the kids after learning about diversifying. Cheers Sharj & team!",
      rating: 5,
    },
    {
      name: "Djamal",
      age: 23,
      content: "Over the past year, we have been assisted with trading and portfolio management. From forex to crypto and meme coins. All are very easy to do with the guides provided by the admins. At the beginning of every week, we are given the breakdown of News events that will occur, plus a breakdown of how the my will play out. This is extremely important for me as I trade forex mainly. I started trading memecoins 3 months ago and at the beginning of my journey, I was absolutely clueless about how to buy and sell these volatile coins. With the help of the admin's guides and also with the help of the chat, which includes 100+ other members, j was able to get on the right track and download the right apps in order to make money. My overall experience with Winsights has been amazing and the calls will forever assist me in managing my portfolio with a consistent capital gain.",
      rating: 5,
    },
    {
      name: "Hassan",
      age: 18,
      content: "Winsights was very helpful it allowed me to minimize time, effort, and incurring losses as I relied upon the expertise of the team. In both forex and crypto, they make great calls but for me particularly I made use of the the frequent and accurate XAUUSD signals which even a beginner could make good money off.",
      rating: 5,
    },
    {
      name: "Kiran",
      age: 22,
      content: "Winsights helped me improve my knowledge of the market 10x. When I joined I had no idea what I was doing and was consistently losing money. When I joined there was a really good community, plenty of guides and learning available and everyone is very helpful. I had so many questions and they were all answered efficiently and with no judgment no matter how simple the questions were. The trades are laid out clearly and were easy to follow and learn from. Since joining I have become a profitable trader in forex, crypto, and stocks 😊",
      rating: 5,
    },
    {
      name: "Kristen",
      age: 23,
      content: "Joining Winsights has been one of the best decisions I've made when it comes to trading. Upon first starting in May, I was intrigued by forex but had 0 knowledge of how it worked, luckily for me 11 NCS featured beginners guides and I was able to 5x my original investment from putting £100 in to start in 4 weeks. Moreover, within two months I have now passed a funded account which was recommended by the group so as to not risk my own capital/obtain higher positions. The group is very helpful and is full of people of all abilities available at every hour of the day, it speaks to the group prosperity that some people who were initially beginners help out other members now and have managed to become self-reliant with respect to forex using their own analysis and acquired knowledge to garner significant profits. More important than how much I've made is learning key skills such as discipline within management and how certain news impacts the prices of commodities. This helps me understand why I have made a profit within my trade and reduce potential losses as not all trades will be winners, as opposed to blindly relying on signals without actually learning the reasons behind a trade.",
      rating: 5,
    },
    {
      name: "Huzaifah",
      age: 19,
      content: "Joined a couple months ago and I was surprised as I didn't know that this group could be as good as it is. The community is great and very active and have now passed two funded accounts because of the accurate signals from the team. This is not to mention the very active crypto side of the group aswell where once again people of all levels of knowledge and financial prowess can succeed, with variance of risk tolerance. I could not recommend the group enough to others and am looking: forward to continuity and growth as I go forth and progress in my own journey.",
      rating: 5,
    },
    {
      name: "Rehan",
      age: 21,
      content: "Winsights has allowed me to increase my knowledge in worldly affairs and general trading including crypto, stocks, and forex. With in-depth analysis and guides, I have been able to make thousands from just a simple click of a button. Aside from that the owners have built an amazing community with support across the board and the chance to Network with like-minded people. Markets CS has also run fundraisers for those in need to allow members to give back with the profits made from the frequent trades admins have posted. Could not recommend enough!",
      rating: 5,
    },
  ],
  faq: [
    {
      question: "Why is the group so cheap?",
      answer: "The group is £30 per month as we believe in a low barrier to entry to learning a skill like trading! We want everyone to be able to learn and capitalise no matter their current wealth status. It is designed for you to leave it.",
    },
    {
      question: "Why is the group on Whatsapp?",
      answer: "We host on Whatsapp mainly due to it's ease, and low barrier of knowledge to use. A lot of new traders have never used Discord before, so to avoid confusion, we use Whatsapp as our main platform, and make it work seamlessly. Discord coming soon, however.",
    },
    {
      question: "What markets do you guys trade?",
      answer: "We trade cryptocurrency, stocks and forex. We do this to give our customers a free selection in how they want to learn and make money!",
    },
    {
      question: "What support do you offer?",
      answer: "We provide in depth guides, 24/7 support, 1:1 mentoring sessions, portfolio management/advice, weekly forex lessons and more!",
    },
    {
      question: "Will I make money?",
      answer: "We try and make sure it is seamless for you to make money, while also learning, with indepth signals, while also teaching you why the trade played out.",
    },
  ],
  howItWorks: {
    title: "How It Works",
    description: "Get started with WINSIGHTS in three simple steps and begin your journey to trading success.",
    steps: [
      {
        title: "Join Winsights",
        description: "Join WINSIGHTS with a simple monthly subscription. Get instant access to all our resources, guides, and community support. Start your trading education journey today!",
      },
      {
        title: "Learn the markets",
        description: "Dive into our comprehensive educational guides covering everything from the basics to advanced strategies. Learn about cryptocurrency, stocks, forex trading, market analysis, and personal finance. Our guides are designed for all skill levels, from complete beginners to experienced traders looking to expand their knowledge.",
      },
      {
        title: "Profit",
        description: "Start profiting through various avenues: invest in your ISA for long-term growth, engage in day trading with our signals and support, or simply become more knowledgeable at work. Apply your new financial knowledge to make better decisions and grow your wealth.",
      },
    ],
  },
  whatWeDo: {
    title: "WHAT WE DO TO HELP YOU!",
    services: [
      {
        title: "24/7 HELP",
        description: "Our staff members are available 24/7 to answer any questions, inquiries, or anything else you may need help with!",
        icon: "chat",
      },
      {
        title: "Easy to use",
        description: "We host our group on Whatsapp, so no need to learn about pesky little Discord or any other platform. We have you covered with everything, on the app you use most.",
        icon: "devices",
      },
      {
        title: "Comprehensive Guides",
        description: "We have perfectly crafted guides to help you set up, and understand the markets. Education in trading is paramount to us, and we portray that with the quality of the guides we provide!",
        icon: "guides",
      },
      {
        title: "1-1 SUPPORT",
        description: "Every week, you can book in a call with one of our expert traders, to pick their brain, or to even understand where you may have difficulties while trading. We also provide portfolio management advice!",
        icon: "support",
      },
    ],
  },
  tradePnL: [
    { id: 1, image: "/images/01e20a18-7407-4547-9efb-48c1be4f0da3.jpg", alt: "Trade PnL - 01e20a18-7407-4547-9efb-48c1be4f0da3" },
    { id: 2, image: "/images/075db817-8abf-47d8-94f6-cd9e39776bf2 (1).jpg", alt: "Trade PnL - 075db817-8abf-47d8-94f6-cd9e39776bf2 (1)" },
    { id: 3, image: "/images/075db817-8abf-47d8-94f6-cd9e39776bf2.jpg", alt: "Trade PnL - 075db817-8abf-47d8-94f6-cd9e39776bf2" },
    { id: 4, image: "/images/10855349-e4ed-47aa-9bf6-8b4429083149.jpg", alt: "Trade PnL - 10855349-e4ed-47aa-9bf6-8b4429083149" },
    { id: 5, image: "/images/1b783bbb-fe9d-4311-9742-d233ff27cadc.jpg", alt: "Trade PnL - 1b783bbb-fe9d-4311-9742-d233ff27cadc" },
    { id: 6, image: "/images/5fe1265a-fad4-4663-907d-bd111fe99dfb.jpg", alt: "Trade PnL - 5fe1265a-fad4-4663-907d-bd111fe99dfb" },
    { id: 7, image: "/images/64e60eb9-c416-4641-90b5-09fc7d2ffd08.jpg", alt: "Trade PnL - 64e60eb9-c416-4641-90b5-09fc7d2ffd08" },
    { id: 8, image: "/images/800f5e94-c395-4c48-a1c6-087ddf42b767.jpg", alt: "Trade PnL - 800f5e94-c395-4c48-a1c6-087ddf42b767" },
    { id: 9, image: "/images/87D9AB14-1D99-486E-A2DC-01BC27AF8593.jpg", alt: "Trade PnL - 87D9AB14-1D99-486E-A2DC-01BC27AF8593" },
    { id: 10, image: "/images/88926765-5077-4ef8-abf4-c028c95c278c.jpg", alt: "Trade PnL - 88926765-5077-4ef8-abf4-c028c95c278c" },
    { id: 11, image: "/images/901fe6eb-5fed-4b54-9097-16dad5ec4b1d.jpg", alt: "Trade PnL - 901fe6eb-5fed-4b54-9097-16dad5ec4b1d" },
    { id: 12, image: "/images/9f8f304f-506d-4eeb-9f07-5d784b837f0b.jpg", alt: "Trade PnL - 9f8f304f-506d-4eeb-9f07-5d784b837f0b" },
    { id: 13, image: "/images/9f9337d1-0cad-42bb-8e37-593a3197e86a.jpg", alt: "Trade PnL - 9f9337d1-0cad-42bb-8e37-593a3197e86a" },
    { id: 14, image: "/images/ADA5DBDC-0529-487A-86F0-C789F4AE79D0.jpg", alt: "Trade PnL - ADA5DBDC-0529-487A-86F0-C789F4AE79D0" },
    { id: 15, image: "/images/AFD63E2C-2E27-404D-A157-AB21167BA073.jpg", alt: "Trade PnL - AFD63E2C-2E27-404D-A157-AB21167BA073" },
    { id: 16, image: "/images/BC16547F-6FD5-41B3-B6D5-202DEAA01B5F.jpg", alt: "Trade PnL - BC16547F-6FD5-41B3-B6D5-202DEAA01B5F" },
    { id: 17, image: "/images/IMG_0197.jpeg", alt: "Trade PnL - IMG 0197" },
    { id: 18, image: "/images/IMG_0209.PNG", alt: "Trade PnL - IMG 0209" },
    { id: 19, image: "/images/IMG_0210.jpeg", alt: "Trade PnL - IMG 0210" },
    { id: 20, image: "/images/IMG_0263.jpeg", alt: "Trade PnL - IMG 0263" },
    { id: 21, image: "/images/IMG_0540.jpeg", alt: "Trade PnL - IMG 0540" },
    { id: 22, image: "/images/IMG_0544.JPG", alt: "Trade PnL - IMG 0544" },
    { id: 23, image: "/images/IMG_0545.JPG", alt: "Trade PnL - IMG 0545" },
    { id: 24, image: "/images/IMG_0546.JPG", alt: "Trade PnL - IMG 0546" },
    { id: 25, image: "/images/IMG_0547.JPG", alt: "Trade PnL - IMG 0547" },
    { id: 26, image: "/images/IMG_0548.JPG", alt: "Trade PnL - IMG 0548" },
    { id: 27, image: "/images/IMG_0549.JPG", alt: "Trade PnL - IMG 0549" },
    { id: 28, image: "/images/IMG_0550.JPG", alt: "Trade PnL - IMG 0550" },
    { id: 29, image: "/images/IMG_0551.JPG", alt: "Trade PnL - IMG 0551" },
    { id: 30, image: "/images/IMG_0552.JPG", alt: "Trade PnL - IMG 0552" },
    { id: 31, image: "/images/IMG_0558.JPG", alt: "Trade PnL - IMG 0558" },
    { id: 32, image: "/images/IMG_0559.JPG", alt: "Trade PnL - IMG 0559" },
    { id: 33, image: "/images/IMG_0563.JPG", alt: "Trade PnL - IMG 0563" },
    { id: 34, image: "/images/IMG_0564.JPG", alt: "Trade PnL - IMG 0564" },
    { id: 35, image: "/images/IMG_0565.JPG", alt: "Trade PnL - IMG 0565" },
    { id: 36, image: "/images/IMG_0566.JPG", alt: "Trade PnL - IMG 0566" },
    { id: 37, image: "/images/IMG_0570.JPG", alt: "Trade PnL - IMG 0570" },
    { id: 38, image: "/images/IMG_0665.jpeg", alt: "Trade PnL - IMG 0665" },
    { id: 39, image: "/images/IMG_1332.jpeg", alt: "Trade PnL - IMG 1332" },
    { id: 40, image: "/images/IMG_1400.jpeg", alt: "Trade PnL - IMG 1400" },
    { id: 41, image: "/images/IMG_1772.jpeg", alt: "Trade PnL - IMG 1772" },
    { id: 42, image: "/images/IMG_1783.jpeg", alt: "Trade PnL - IMG 1783" },
    { id: 43, image: "/images/IMG_1789.jpeg", alt: "Trade PnL - IMG 1789" },
    { id: 44, image: "/images/IMG_1872.jpeg", alt: "Trade PnL - IMG 1872" },
    { id: 45, image: "/images/IMG_1905.jpeg", alt: "Trade PnL - IMG 1905" },
    { id: 46, image: "/images/IMG_1914.jpeg", alt: "Trade PnL - IMG 1914" },
    { id: 47, image: "/images/IMG_1926.jpeg", alt: "Trade PnL - IMG 1926" },
    { id: 48, image: "/images/IMG_1928.jpeg", alt: "Trade PnL - IMG 1928" },
    { id: 49, image: "/images/IMG_1987.jpeg", alt: "Trade PnL - IMG 1987" },
    { id: 50, image: "/images/IMG_3070.jpeg", alt: "Trade PnL - IMG 3070" },
    { id: 51, image: "/images/IMG_4965.jpeg", alt: "Trade PnL - IMG 4965" },
    { id: 52, image: "/images/IMG_5030.jpeg", alt: "Trade PnL - IMG 5030" },
    { id: 53, image: "/images/IMG_5033.jpeg", alt: "Trade PnL - IMG 5033" },
    { id: 54, image: "/images/IMG_5435.PNG", alt: "Trade PnL - IMG 5435" },
    { id: 55, image: "/images/IMG_5448.jpeg", alt: "Trade PnL - IMG 5448" },
    { id: 56, image: "/images/IMG_5495.jpeg", alt: "Trade PnL - IMG 5495" },
    { id: 57, image: "/images/IMG_6745.jpeg", alt: "Trade PnL - IMG 6745" },
    { id: 58, image: "/images/IMG_7358.jpeg", alt: "Trade PnL - IMG 7358" },
    { id: 59, image: "/images/IMG_7544.jpeg", alt: "Trade PnL - IMG 7544" },
    { id: 60, image: "/images/IMG_7560.jpeg", alt: "Trade PnL - IMG 7560" },
    { id: 61, image: "/images/IMG_7580.jpeg", alt: "Trade PnL - IMG 7580" },
    { id: 62, image: "/images/IMG_8942.jpeg", alt: "Trade PnL - IMG 8942" },
    { id: 63, image: "/images/a9531ea6-bfdd-4867-a4de-682171f65c3f.jpg", alt: "Trade PnL - a9531ea6-bfdd-4867-a4de-682171f65c3f" },
    { id: 64, image: "/images/ba0ffd76-484a-4207-9ef8-326896111ece.jpg", alt: "Trade PnL - ba0ffd76-484a-4207-9ef8-326896111ece" },
    { id: 65, image: "/images/bd1fea82-e0a4-491f-b4ef-6be634f5194e.jpg", alt: "Trade PnL - bd1fea82-e0a4-491f-b4ef-6be634f5194e" },
    { id: 66, image: "/images/dba900e0-a206-4947-9d21-bd38a491b9ff.jpg", alt: "Trade PnL - dba900e0-a206-4947-9d21-bd38a491b9ff" },
    { id: 67, image: "/images/e6454e07-f6d5-45e4-bd24-f6e64470d4d9.jpg", alt: "Trade PnL - e6454e07-f6d5-45e4-bd24-f6e64470d4d9" },
    { id: 68, image: "/images/f881ee5a-bef7-4dd8-8dde-38f1f231d305.jpg", alt: "Trade PnL - f881ee5a-bef7-4dd8-8dde-38f1f231d305" },
  ],
  tradingSignals: {
    title: "Our signals, your education, your profits",
    cards: [
      {
        title: "CRYPTO",
        description: "Crypto is a scam? We've heard that too, How would you feel if you learned what cryptocurrency was before you invested? That's exactly What we do at Winsights, we prioritize knowledge first, so you can learn, earn, and be comfortable with what you invest in.",
        buttonText: "TRADE CRYPTO!",
        buttonUrl: "https://buy.stripe.com/aEU9AVdWd7GU4iAaEM",
      },
      {
        title: "STOCKS",
        description: "Our in-house stock market specialists, always know what narratives to catch, and when to invest, and also provide portfolio management. Not only options, and futures, but ISA help too! Did I mention we trade earnings too, with detailed reports?",
        buttonText: "TRADE STOCKS!",
        buttonUrl: "https://buy.stripe.com/aEU9AVdWd7GU4iAaEM",
      },
      {
        title: "FOREX",
        description: "Forex is the most lucrative of them all! Dive into a world of earning and learning. With Our economic experts in the group, we are able to predict the market moves during big economic data prints, as well as perfecting trades for all currency pairs!",
        buttonText: "TRADE FOREX!",
        buttonUrl: "https://buy.stripe.com/aEU9AVdWd7GU4iAaEM",
      },
    ],
  },
};

